// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANutDkcCKX7OKQNbuFXlcRufAl0snoLwg',
    appId: '1:924241386528:web:ebbbcca71422b68e61f045',
    messagingSenderId: '924241386528',
    projectId: 'task-manager-9e6f5',
    authDomain: 'task-manager-9e6f5.firebaseapp.com',
    storageBucket: 'task-manager-9e6f5.firebasestorage.app',
    measurementId: 'G-CSHM6RYJQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmXw22-0W_zwoYzo31SUalK9PSIe6RYg',
    appId: '1:924241386528:android:867964453fb919a261f045',
    messagingSenderId: '924241386528',
    projectId: 'task-manager-9e6f5',
    storageBucket: 'task-manager-9e6f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBET_nirdt_hdrffLXtgoYJCVydQzGVIQw',
    appId: '1:924241386528:ios:c91f19bda5f48a2261f045',
    messagingSenderId: '924241386528',
    projectId: 'task-manager-9e6f5',
    storageBucket: 'task-manager-9e6f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBET_nirdt_hdrffLXtgoYJCVydQzGVIQw',
    appId: '1:924241386528:ios:c91f19bda5f48a2261f045',
    messagingSenderId: '924241386528',
    projectId: 'task-manager-9e6f5',
    storageBucket: 'task-manager-9e6f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterActivity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANutDkcCKX7OKQNbuFXlcRufAl0snoLwg',
    appId: '1:924241386528:web:a10d86c1e918f82f61f045',
    messagingSenderId: '924241386528',
    projectId: 'task-manager-9e6f5',
    authDomain: 'task-manager-9e6f5.firebaseapp.com',
    storageBucket: 'task-manager-9e6f5.firebasestorage.app',
    measurementId: 'G-1ME9HE0GLR',
  );
}
